project:
  type: website
  output-dir: docs
  resources:
    - "Diana_Pachon_Resume.pdf"

website:
  title: "Alejandra Pachon"
  favicon: favicon.svg
  navbar:
    background: "#272A2A"
    foreground: "#E0E0D4"
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: skills.qmd
        text: Skills
      - href: leadership.qmd
        text: Leadership
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
